### ISSUE TITLE
After instance is registered with OUT_OF_SERVICE, following UP hartbeats are ignored

### ISSUE THREAD

**Issue by OlgaMaciaszek** [Netflix/eureka#1398] opened 2021-05-24 13:23 UTC
We've had [this issue](https://github.com/spring-cloud/spring-cloud-netflix/issues/3941) created in Spring Cloud Netflix. The root cause seems to be that after the service registers with `OUT_OF_SERVICE` any following `UP` heartbeats are being ignored (see [comment](https://github.com/spring-cloud/spring-cloud-netflix/issues/3941#issuecomment-747322635)).

**Comment by troshko111** [comment] 2021-05-25 22:31
This is not a bug, but an invalid transition performed by the Eureka client, the client may not report this status itself, it's a reserved server status, have the client report `STARTING -> UP` to signal readiness, see more detailed description in the linked issue. Closing.

**Closed by troshko111** 2021-05-25 22:31 UTC
