### ISSUE TITLE
Eureka sample service periodically fails when client connects

### ISSUE THREAD

**Issue by lenadroid** [Netflix/eureka#766] opened 2016-03-18 00:56 UTC
I am following the example from this repo.
Eureka server is running on localhost:8080.

As a next step I attempt to run the sample service, like this:

`    ./gradlew :eureka-examples:runExampleService`

Here is the output that I get:

```
$ ./gradlew :eureka-examples:runExampleService --stacktrace
    Inferred project: eureka, version: 1.4.6-SNAPSHOT
    Publication mavenNebula not found in project :.
    [buildinfo] Properties file path was not found! (Relevant only for builds running on a CI Server)
    Publication named 'mavenNebula' does not exist for project ':' in task ':artifactoryPublish'.
    None of the specified publications matched for project ':' - nothing to publish.
    :eureka-client:compileJava UP-TO-DATE
    :eureka-client:processResources UP-TO-DATE
    :eureka-client:classes UP-TO-DATE
    :eureka-client:writeManifestProperties UP-TO-DATE
    :eureka-client:jar
    :eureka-examples:compileJava
    warning: [options] bootstrap class path not set in conjunction with -source 1.7
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    1 warning
    :eureka-examples:processResources UP-TO-DATE
    :eureka-examples:classes
    :eureka-examples:runExampleService
    [main] WARN com.netflix.config.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
    [main] INFO com.netflix.config.sources.URLConfigurationSource - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
    [main] INFO com.netflix.config.DynamicPropertyFactory - DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@46ee7fe8
    [main] INFO com.netflix.config.util.ConfigurationUtils - Loaded properties file file:/Users/lenok/Documents/Programming/Github/eureka/eureka-examples/conf/sample-eureka-service.properties
    [main] WARN com.netflix.config.util.ConfigurationUtils - file:/Users/lenok/Documents/Programming/Github/eureka/eureka-examples/conf/sample-eureka-service.properties is already loaded
    [main] INFO com.netflix.appinfo.providers.EurekaConfigBasedInstanceInfoProvider - Setting initial instance status as: STARTING
    [main] INFO com.netflix.discovery.provider.DiscoveryJerseyProvider - Using JSON encoding codec LegacyJacksonJson
    [main] INFO com.netflix.discovery.provider.DiscoveryJerseyProvider - Using JSON decoding codec LegacyJacksonJson
    [main] INFO com.netflix.discovery.provider.DiscoveryJerseyProvider - Using XML encoding codec XStreamXml
    [main] INFO com.netflix.discovery.provider.DiscoveryJerseyProvider - Using XML decoding codec XStreamXml
    [main] INFO com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver - Resolving eureka endpoints via configuration
    [main] INFO com.netflix.discovery.DiscoveryClient - Disable delta property : false
    [main] INFO com.netflix.discovery.DiscoveryClient - Single vip registry refresh property : null
    [main] INFO com.netflix.discovery.DiscoveryClient - Force full registry fetch : false
    [main] INFO com.netflix.discovery.DiscoveryClient - Application is null : false
    [main] INFO com.netflix.discovery.DiscoveryClient - Registered Applications size is zero : true
    [main] INFO com.netflix.discovery.DiscoveryClient - Application version is -1: true
    [main] INFO com.netflix.discovery.DiscoveryClient - Getting all instance registry info from the eureka server
    [main] INFO com.netflix.discovery.DiscoveryClient - The response status is 200
    [main] INFO com.netflix.discovery.DiscoveryClient - Starting heartbeat executor: renew interval is: 30
    [main] INFO com.netflix.discovery.InstanceInfoReplicator - InstanceInfoReplicator onDemand update allowed rate per min is 4
    Registering service to eureka with STARTING status
    Simulating service initialization by sleeping for 2 seconds...
    Done sleeping, now changing status to UP
    [main] INFO com.netflix.discovery.DiscoveryClient - Saw local status change event StatusChangeEvent [timestamp=1458260744041, current=UP, previous=STARTING]
    Waiting ... verifying service registration with eureka ...
    [DiscoveryClient-InstanceInfoReplicator-0] INFO com.netflix.discovery.DiscoveryClient - DiscoveryClient_SAMPLEREGISTERINGSERVICE/Alenas-MacBook-Pro.local: registering service...
    [DiscoveryClient-InstanceInfoReplicator-0] INFO com.netflix.discovery.DiscoveryClient - DiscoveryClient_SAMPLEREGISTERINGSERVICE/Alenas-MacBook-Pro.local - registration status: 204
    Waiting ... verifying service registration with eureka ...
    Waiting ... verifying service registration with eureka ...
    Service started and ready to process requests..
    > Building 88% > :eureka-examples:runExampleService
```

After I start the client, like this:

```
$ ./gradlew :eureka-examples:runExampleClient
    Inferred project: eureka, version: 1.4.6-SNAPSHOT
    Publication mavenNebula not found in project :.
    [buildinfo] Properties file path was not found! (Relevant only for builds running on a CI Server)
    Publication named 'mavenNebula' does not exist for project ':' in task ':artifactoryPublish'.
    None of the specified publications matched for project ':' - nothing to publish.
    :eureka-client:compileJava UP-TO-DATE
    :eureka-client:processResources UP-TO-DATE
    :eureka-client:classes UP-TO-DATE
    :eureka-client:writeManifestProperties UP-TO-DATE
    :eureka-client:jar
    :eureka-examples:compileJava
    warning: [options] bootstrap class path not set in conjunction with -source 1.7
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    1 warning
    :eureka-examples:processResources UP-TO-DATE
    :eureka-examples:classes
    :eureka-examples:runExampleClient
    [main] WARN com.netflix.config.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
    [main] INFO com.netflix.config.sources.URLConfigurationSource - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
    [main] INFO com.netflix.config.DynamicPropertyFactory - DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@46ee7fe8
    [main] INFO com.netflix.config.util.ConfigurationUtils - Loaded properties file file:/Users/lenok/Documents/Programming/Github/eureka/eureka-examples/conf/sample-eureka-client.properties
    [main] WARN com.netflix.config.util.ConfigurationUtils - file:/Users/lenok/Documents/Programming/Github/eureka/eureka-examples/conf/sample-eureka-client.properties is already loaded
    [main] INFO com.netflix.appinfo.providers.EurekaConfigBasedInstanceInfoProvider - Setting initial instance status as: STARTING
    [main] INFO com.netflix.discovery.provider.DiscoveryJerseyProvider - Using JSON encoding codec LegacyJacksonJson
    [main] INFO com.netflix.discovery.provider.DiscoveryJerseyProvider - Using JSON decoding codec JacksonJson
    [main] INFO com.netflix.discovery.provider.DiscoveryJerseyProvider - Using XML encoding codec XStreamXml
    [main] INFO com.netflix.discovery.provider.DiscoveryJerseyProvider - Using XML decoding codec XStreamXml
    [main] INFO com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver - Resolving eureka endpoints via configuration
    [main] INFO com.netflix.discovery.DiscoveryClient - Disable delta property : false
    [main] INFO com.netflix.discovery.DiscoveryClient - Single vip registry refresh property : null
    [main] INFO com.netflix.discovery.DiscoveryClient - Force full registry fetch : false
    [main] INFO com.netflix.discovery.DiscoveryClient - Application is null : false
    [main] INFO com.netflix.discovery.DiscoveryClient - Registered Applications size is zero : true
    [main] INFO com.netflix.discovery.DiscoveryClient - Application version is -1: true
    [main] INFO com.netflix.discovery.DiscoveryClient - Getting all instance registry info from the eureka server
    [main] INFO com.netflix.discovery.DiscoveryClient - The response status is 200
    [main] INFO com.netflix.discovery.DiscoveryClient - Not registering with Eureka server per configuration
    Found an instance of example service to talk to from eureka: sampleservice.mydomain.net:8001
    healthCheckUrl: http://Alenas-MacBook-Pro.local:8001/healthcheck
    override: UNKNOWN
    Connected to server. Sending a sample request: FOO Thu Mar 17 17:11:33 PDT 2016
    Waiting for server response..
    Received response from server: BAR Thu Mar 17 17:11:33 PDT 2016
    Exiting the client. Demo over..
    
    BUILD SUCCESSFUL
    
    Total time: 9.497 secs
```

It basically connects to the server and waits for response, etc.

At the same time on the service terminal I see the following happening. Sometimes when I do these actions I see the successful response on the eureka service:

```
  Client got connected... processing request from the client
    Received a request from the example client: FOO Thu Mar 17 17:30:16 PDT 2016
    Sending the response to the client: BAR Thu Mar 17 17:30:16 PDT 2016
    Simulating service doing work by sleeping for 10 seconds...
    Removing registration from eureka
    [main] INFO com.netflix.discovery.DiscoveryClient - DiscoveryClient_SAMPLEREGISTERINGSERVICE/Alenas-MacBook-Pro.local - deregister  status: 200
    Shutting down server. Demo over.
    
    BUILD SUCCESSFUL
    
    Total time: 4 mins 53.331 secs

```
And sometimes it gives errors, like here:

```
 Client got connected... processing request from the client
    Received a request from the example client: FOO Thu Mar 17 17:33:30 PDT 2016
    Sending the response to the client: BAR Thu Mar 17 17:33:30 PDT 2016
    Simulating service doing work by sleeping for 10 seconds...
    Removing registration from eureka
    Exception in thread "main" java.lang.NoClassDefFoundError: com/netflix/discovery/shared/transport/decorator/EurekaHttpClientDecorator$2
    	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.cancel(EurekaHttpClientDecorator.java:71)
    	at com.netflix.discovery.DiscoveryClient.unregister(DiscoveryClient.java:886)
    	at com.netflix.discovery.DiscoveryClient.shutdown(DiscoveryClient.java:869)
    	at com.netflix.eureka.ExampleServiceBase.stop(ExampleServiceBase.java:89)
    	at com.netflix.eureka.ExampleServiceBase.start(ExampleServiceBase.java:80)
    	at com.netflix.eureka.ExampleEurekaService.main(ExampleEurekaService.java:45)
    Caused by: java.lang.ClassNotFoundException: com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$2
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    	... 6 more
    :eureka-examples:runExampleService FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':eureka-examples:runExampleService'.
    > Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
    
    * Try:
    Run with --info or --debug option to get more log output.
    
    * Exception is:
    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':eureka-examples:runExampleService'.
    	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
    	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
    	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
    	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
    	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
    	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
    	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
    	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
    	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
    	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
    	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
    	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
    	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
    	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
    	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
    	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
    	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
    	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
    	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
    	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
    	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
    	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
    	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    	at org.gradle.launcher.Main.doAction(Main.java:33)
    	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
    	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
    	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
    	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
    	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
    Caused by: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
    	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:365)
    	at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:31)
    	at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:60)
    	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
    	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
    	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
    	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
    	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
    	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    	... 47 more
    
    
    BUILD FAILED
    
    Total time: 1 mins 1.267 secs
```

What might be the problem?

**Comment by qiangdavidliu** [comment] 2016-03-30 19:54
@lenadroid are you running the client and server from the same git repo? Wondering if there may be a version mismatch somewhere as the server has a dependency on the client also.

**Comment by lenadroid** [comment] 2016-03-30 19:56
@qiangdavidliu yeah, from the same.

**Comment by qiangdavidliu** [comment] 2016-04-13 00:26
@lenadroid this is a pretty weird one. The class that's failing with ClassNotFound is there, and your successful executions also prove that. Are you able to see the same sort of problems with a more complicated set up than the simple examples provided?

**Comment by SphereUser** [comment] 2016-04-25 20:05
eureka is pretty unstable and avoid to use it in serious applications.

**Comment by qiangdavidliu** [comment] 2016-04-25 21:14
@SphereUser I'm curious to the unstability that you are seeing. We internally run eureka at very large scale and it has been stable for many years. One thing we are trying to update is documentation on configuration and operation of the servers, which currently on github is lacking some advanced info.

**Comment by qiangdavidliu** [comment] 2016-05-27 20:40
Closing this issue as the problem is specific (after more investigation) for the example when ran with gradle using the gradle applications plugin. Using the dist option and also in real operation the ClassNotFoundExceptions are not seen.

**Closed by qiangdavidliu** 2016-05-27 20:40 UTC
